server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /data/mephi-web;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
